
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'swarm'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'dockerd-export'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-export'
      type: 'A'
      port: 9323